FROM node:14
WORKDIR /apibiziidi
COPY package*.json ./
RUN npm install
ENV ACCESS_TOKEN_SECRET= ${ACCESS_TOKEN_SECRET}
ENV PORT= ${PORT}
ENV HOST= ${HOST}
ENV PASSWORD= ${PASSWORD} 
ENV PORT_EMAIL= ${PORT_EMAIL}
ENV URI_PRODUCTION= ${URI_PRODUCTION}
ENV USER_EMAIL= ${USER_EMAIL}
ENV NODE_ENV= Production
COPY /src ./
CMD ["npm", "start"]
