# This is a basic workflow to help you get started with Actions
name: WorkflowAPIDiidxaza

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the release branch
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkhout the code
      uses: actions/checkout@v2
    
    - name: Create env file
        run: |
          touch .env
          echo URI = $URI >> .env
          echo ACCESS_TOKEN_SECRET = ${{ secrets.ACCESS_TOKEN_SECRET }} >> .env
          echo PORT = ${{ secrets.PORT }} >> .env
          echo HOST = ${{ secrets.HOST }} >> .env
          echo PASSWORD = ${{ secrets.PASSWORD }} >> .env
          echo PORT_EMAIL = ${{ secrets.PORT_EMAIL }} >> .env
          echo URI_PRODUCTION = ${{ secrets.URI_PRODUCTION }} >> .env
          echo URI_TEST = ${{ secrets.URI_TEST }} >> .env
          echo USER_EMAIL = ${{ secrets.USER_EMAIL }} >> .env
          echo NODE_ENV = Production
    - name: Setup Node
      uses: actions/setup-node@v1

    - run: npm ci
    - run: npm test
    - run: npm run build