# This is a basic workflow to help you get started with Actions
name: WorkflowAPIDiidxaza

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the release branch
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkhout the code
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with: 
        node-version: 14.x
    
    - name: Install dependencies
      run: npm ci

  tests:
    needs: [build]
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
      PORT: ${{ secrets.PORT }}
      HOST: ${{ secrets.HOST }}
      PASSWORD: ${{ secrets.PASSWORD }} 
      PORT_EMAIL: ${{ secrets.PORT_EMAIL }}
      URI_TEST: ${{ secrets.URI_TEST }}
      USER_EMAIL: ${{ secrets.USER_EMAIL }}
      NODE_ENV: test
    steps:
    - name: Checkhout the code
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with: 
        node-version: 14.x
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm run test-html

    - name: Upload test report
      uses: actions/upload-artifact@v2
      with:
        name: test_report
        path: tests/reports
  
  build-image:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2

      #- name: Install buildx
        #id: buildx
        #uses: crazy-max/ghaction-docker-buildx@v1
        #with:
          #version: latest
      #- name: Login to Docker Hub
        #run: echo "${{secrets.PASSWORD_DOCKERHUB}}" | docker login -u "${{secrets.USERNAME_DOCKERHUB}}" --password-stdin
      #- name: Build the image
        #run: |
          #docker buildx build --push \
            #--tag ${{secrets.USERNAME_DOCKERHUB}}/apibiziididiidxaza:lastest \
            #--platform linux/arm64,linux/arm/v7 .
      - name: login-dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.USERNAME_DOCKERHUB}}
          password: ${{secrets.PASSWORD_DOCKERHUB}}
        
      - name: qemu
        uses: docker/setup-qemu-action@v1
      - name: build-x
        uses: docker/setup-buildx-action@v1
      - name: build-push-image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm64
          push: true
          tags: ${{secrets.USERNAME_DOCKERHUB}}/apibiziididiidxaza:lastest