# This is a basic workflow to help you get started with Actions
name: WorkflowAPIDiidxaza

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the release branch
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
      PORT: ${{ secrets.PORT }}
      HOST: ${{ secrets.HOST }}
      PASSWORD: ${{ secrets.PASSWORD }} 
      PORT_EMAIL: ${{ secrets.PORT_EMAIL }}
      URI_PRODUCTION: ${{ secrets.URI_PRODUCTION }}
      URI_TEST: ${{ secrets.URI_TEST }}
      USER_EMAIL: ${{ secrets.USER_EMAIL }}
      NODE_ENV: test
    steps:
    - name: Checkhout the code
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with: 
        node-version: 14.x
    
    - name: Install dependencies
      run: npm ci

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      run: npm run test-html

    - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: test_report
          path: test/reports